/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RbmsRouteRouteImport } from './routes/_rbms/route'
import { Route as RbmsIndexRouteImport } from './routes/_rbms/index'
import { Route as RbmsActivityLogsRouteImport } from './routes/_rbms/activity-logs'
import { Route as RbmsAgentsIndexRouteImport } from './routes/_rbms/agents/index'
import { Route as RbmsAgentsAgentIdRouteImport } from './routes/_rbms/agents/$agentId'
import { Route as RbmsFpcsIndexRouteImport } from './routes/_rbms/fpcs/index'
import { Route as RbmsFpcsFpcIdRouteImport } from './routes/_rbms/fpcs/$fpcId'
import { Route as RbmsShgsIndexRouteImport } from './routes/_rbms/shgs/index'
import { Route as RbmsShgsShgIdIndexRouteImport } from './routes/_rbms/shgs/$shgId/index'
import { Route as RbmsShgsShgIdFarmersFarmerIdRouteImport } from './routes/_rbms/shgs/$shgId/farmers/$farmerId'

const RbmsRouteRoute = RbmsRouteRouteImport.update({
  id: '/_rbms',
  getParentRoute: () => rootRouteImport,
} as any)
const RbmsIndexRoute = RbmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsActivityLogsRoute = RbmsActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsAgentsIndexRoute = RbmsAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsAgentsAgentIdRoute = RbmsAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsFpcsIndexRoute = RbmsFpcsIndexRouteImport.update({
  id: '/fpcs/',
  path: '/fpcs/',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsFpcsFpcIdRoute = RbmsFpcsFpcIdRouteImport.update({
  id: '/fpcs/$fpcId',
  path: '/fpcs/$fpcId',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsShgsIndexRoute = RbmsShgsIndexRouteImport.update({
  id: '/shgs/',
  path: '/shgs/',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsShgsShgIdIndexRoute = RbmsShgsShgIdIndexRouteImport.update({
  id: '/shgs/$shgId/',
  path: '/shgs/$shgId/',
  getParentRoute: () => RbmsRouteRoute,
} as any)
const RbmsShgsShgIdFarmersFarmerIdRoute =
  RbmsShgsShgIdFarmersFarmerIdRouteImport.update({
    id: '/shgs/$shgId/farmers/$farmerId',
    path: '/shgs/$shgId/farmers/$farmerId',
    getParentRoute: () => RbmsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RbmsIndexRoute
  '/activity-logs': typeof RbmsActivityLogsRoute
  '/agents/$agentId': typeof RbmsAgentsAgentIdRoute
  '/fpcs/$fpcId': typeof RbmsFpcsFpcIdRoute
  '/agents/': typeof RbmsAgentsIndexRoute
  '/fpcs/': typeof RbmsFpcsIndexRoute
  '/shgs/': typeof RbmsShgsIndexRoute
  '/shgs/$shgId/': typeof RbmsShgsShgIdIndexRoute
  '/shgs/$shgId/farmers/$farmerId': typeof RbmsShgsShgIdFarmersFarmerIdRoute
}
export interface FileRoutesByTo {
  '/activity-logs': typeof RbmsActivityLogsRoute
  '/': typeof RbmsIndexRoute
  '/agents/$agentId': typeof RbmsAgentsAgentIdRoute
  '/fpcs/$fpcId': typeof RbmsFpcsFpcIdRoute
  '/agents': typeof RbmsAgentsIndexRoute
  '/fpcs': typeof RbmsFpcsIndexRoute
  '/shgs': typeof RbmsShgsIndexRoute
  '/shgs/$shgId': typeof RbmsShgsShgIdIndexRoute
  '/shgs/$shgId/farmers/$farmerId': typeof RbmsShgsShgIdFarmersFarmerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_rbms': typeof RbmsRouteRouteWithChildren
  '/_rbms/activity-logs': typeof RbmsActivityLogsRoute
  '/_rbms/': typeof RbmsIndexRoute
  '/_rbms/agents/$agentId': typeof RbmsAgentsAgentIdRoute
  '/_rbms/fpcs/$fpcId': typeof RbmsFpcsFpcIdRoute
  '/_rbms/agents/': typeof RbmsAgentsIndexRoute
  '/_rbms/fpcs/': typeof RbmsFpcsIndexRoute
  '/_rbms/shgs/': typeof RbmsShgsIndexRoute
  '/_rbms/shgs/$shgId/': typeof RbmsShgsShgIdIndexRoute
  '/_rbms/shgs/$shgId/farmers/$farmerId': typeof RbmsShgsShgIdFarmersFarmerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/agents/$agentId'
    | '/fpcs/$fpcId'
    | '/agents/'
    | '/fpcs/'
    | '/shgs/'
    | '/shgs/$shgId/'
    | '/shgs/$shgId/farmers/$farmerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity-logs'
    | '/'
    | '/agents/$agentId'
    | '/fpcs/$fpcId'
    | '/agents'
    | '/fpcs'
    | '/shgs'
    | '/shgs/$shgId'
    | '/shgs/$shgId/farmers/$farmerId'
  id:
    | '__root__'
    | '/_rbms'
    | '/_rbms/activity-logs'
    | '/_rbms/'
    | '/_rbms/agents/$agentId'
    | '/_rbms/fpcs/$fpcId'
    | '/_rbms/agents/'
    | '/_rbms/fpcs/'
    | '/_rbms/shgs/'
    | '/_rbms/shgs/$shgId/'
    | '/_rbms/shgs/$shgId/farmers/$farmerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RbmsRouteRoute: typeof RbmsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rbms': {
      id: '/_rbms'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof RbmsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rbms/': {
      id: '/_rbms/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RbmsIndexRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/activity-logs': {
      id: '/_rbms/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof RbmsActivityLogsRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/agents/': {
      id: '/_rbms/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof RbmsAgentsIndexRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/agents/$agentId': {
      id: '/_rbms/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof RbmsAgentsAgentIdRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/fpcs/': {
      id: '/_rbms/fpcs/'
      path: '/fpcs'
      fullPath: '/fpcs/'
      preLoaderRoute: typeof RbmsFpcsIndexRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/fpcs/$fpcId': {
      id: '/_rbms/fpcs/$fpcId'
      path: '/fpcs/$fpcId'
      fullPath: '/fpcs/$fpcId'
      preLoaderRoute: typeof RbmsFpcsFpcIdRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/shgs/': {
      id: '/_rbms/shgs/'
      path: '/shgs'
      fullPath: '/shgs/'
      preLoaderRoute: typeof RbmsShgsIndexRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/shgs/$shgId/': {
      id: '/_rbms/shgs/$shgId/'
      path: '/shgs/$shgId'
      fullPath: '/shgs/$shgId/'
      preLoaderRoute: typeof RbmsShgsShgIdIndexRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
    '/_rbms/shgs/$shgId/farmers/$farmerId': {
      id: '/_rbms/shgs/$shgId/farmers/$farmerId'
      path: '/shgs/$shgId/farmers/$farmerId'
      fullPath: '/shgs/$shgId/farmers/$farmerId'
      preLoaderRoute: typeof RbmsShgsShgIdFarmersFarmerIdRouteImport
      parentRoute: typeof RbmsRouteRoute
    }
  }
}

interface RbmsRouteRouteChildren {
  RbmsActivityLogsRoute: typeof RbmsActivityLogsRoute
  RbmsIndexRoute: typeof RbmsIndexRoute
  RbmsAgentsAgentIdRoute: typeof RbmsAgentsAgentIdRoute
  RbmsFpcsFpcIdRoute: typeof RbmsFpcsFpcIdRoute
  RbmsAgentsIndexRoute: typeof RbmsAgentsIndexRoute
  RbmsFpcsIndexRoute: typeof RbmsFpcsIndexRoute
  RbmsShgsIndexRoute: typeof RbmsShgsIndexRoute
  RbmsShgsShgIdIndexRoute: typeof RbmsShgsShgIdIndexRoute
  RbmsShgsShgIdFarmersFarmerIdRoute: typeof RbmsShgsShgIdFarmersFarmerIdRoute
}

const RbmsRouteRouteChildren: RbmsRouteRouteChildren = {
  RbmsActivityLogsRoute: RbmsActivityLogsRoute,
  RbmsIndexRoute: RbmsIndexRoute,
  RbmsAgentsAgentIdRoute: RbmsAgentsAgentIdRoute,
  RbmsFpcsFpcIdRoute: RbmsFpcsFpcIdRoute,
  RbmsAgentsIndexRoute: RbmsAgentsIndexRoute,
  RbmsFpcsIndexRoute: RbmsFpcsIndexRoute,
  RbmsShgsIndexRoute: RbmsShgsIndexRoute,
  RbmsShgsShgIdIndexRoute: RbmsShgsShgIdIndexRoute,
  RbmsShgsShgIdFarmersFarmerIdRoute: RbmsShgsShgIdFarmersFarmerIdRoute,
}

const RbmsRouteRouteWithChildren = RbmsRouteRoute._addFileChildren(
  RbmsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RbmsRouteRoute: RbmsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
